[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.20.1", features = ["full"]}
zeroize = "1.3.0"
rsa = "0.5.0"
x25519-dalek = "1.2.0"
rand_core = { version = "0.5", default-features = false }
sha3 = "0.10.2"
bytes = "1.2.1"
lib = {path = "../lib"}